kafka:
  broker:
    address: myServer:9092
  zookeeper:
    connect: myServer:2181
  topic: "test"
  messageKey:
zookeeper:
  host: myServer
  port: 2181
mq:
  enabled: true
cassandra:
  address: myServer
  port: 9042