kafka:
  broker:
    address: localhost:9092
  zookeeper:
    connect: localhost:2181
  topic: "test"
  messageKey:
zookeeper:
  host: localhost
  port: 2181
mq:
  enabled: true
cassandra:
  address: localhost
  port: 9042